# Generated by Django 5.0.2 on 2024-02-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Risk_Analyser'), (3, ' Risk_Monitor')], default=3, null=True),
        ),
    ]
