# Generated by Django 5.0.2 on 2024-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0003_alter_user_options_user_is_deleted_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='roles',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Risk_Analyser'), (3, ' Risk_Monitor')], default=3),
        ),
    ]
