# Generated by Django 5.0.2 on 2024-07-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0004_rename_role_role_roles_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='username',
        ),
    ]
