# Generated by Django 5.0.2 on 2024-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0005_remove_role_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Risk Analyser'), (3, ' Risk Monitor')], default=3),
        ),
    ]
