# Generated by Django 5.0.2 on 2024-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Risk Analyser'), (3, 'Risk Monitor')], default=3),
        ),
    ]
